### ISSUE TITLE
requests without shared secret

### ISSUE THREAD

**Issue by gk-fschubert** [radsecproxy/radsecproxy#143]
Hi there, 
I hopefully have something configured wrongly. 

Normally I'm testing authentications with eapol_test and if I leave the shared secret empty for an authentication, radsecproxy rejects that because the shared secret is wrong. 

But a colleague came in the hand of a tool called NTRadPing and there no matter what you type into the shared secret or leave it empty, radsecproxy is forwarding those requests to the radsec servers. 

radsecproxy.conf
```

ListenUDP       *:1812
ListenUDP       *:1813
LogLevel        3
LogFullUsername on
LogMAC          Original
LoopPrevention  on
tls default {
    CACertificateFile = /etc/ca.crt
    CertificateFile = /etc/servercert.pem
    CertificateKeyFile = /etc/servercert.key
}
rewrite default {
    AddAttribute 126:proxy
}
client default {
    host 0.0.0.0/0
    type udp
    secret test stuff 
}

server server-tls-main {
    host host.docker.internal
    port 2083
    type tls
    secret radsec
    CertificateNameCheck off
    TCPKeepalive on
}

server server-tls-secondary {
    host 143.244.197.235
    port 2083
    type tls
    secret radsec
    CertificateNameCheck off
    TCPKeepalive on
}


realm * {
    server server-tls-main
accountingserver server-tls-main
server server-tls-secondary
accountingserver server-tls-secondary

    accountingresponse on
}
```

NTRadPing settings: 
![image](https://github.com/radsecproxy/radsecproxy/assets/41149338/57747f04-94ad-4703-a446-7d5f47825186)

radsecproxy log: 
```
Apr 12 14:25:33 2024: freerealm: called with refcount 6
Fri Apr 12 14:25:33 2024: clientwr: got new request
Fri Apr 12 14:25:33 2024: clientradputtls: Sent 76 bytes, Radius packet of length 76 to TLS peer server-tls-secondary
Fri Apr 12 14:25:34 2024: radtlsget: got 39 bytes
Fri Apr 12 14:25:34 2024: got Access-Reject message with id 34
Fri Apr 12 14:25:34 2024: Access-Reject for user test-hello from server-tls-secondary to default (172.18.0.1) operator proxy
Fri Apr 12 14:25:34 2024: replyh: passing Access-Reject (id 38) to client default (172.18.0.1)
Fri Apr 12 14:25:34 2024: signalling server writer
Fri Apr 12 14:25:34 2024: freerq: called with refcount 3
Fri Apr 12 14:25:34 2024: udp server writer, got signal
Fri Apr 12 14:25:34 2024: udpserverwr: refcount 2
Fri Apr 12 14:25:34 2024: freerq: called with refcount 2
Fri Apr 12 14:25:34 2024: udp server writer, waiting for signal
```

**Comment by fmauchle** [comment]
Yes, this is (sadly) the expected behaviour of 'traditional' radius RFC 2865.
Really the best thing to do is use radius over TLS (radsec), which obviously you are already doing, and keep UDP path as short as possible.

In the plain radius case (without any extension) the shared secret is used to encrypt (well, to day it's more like an obfuscation, since its MD5) only the user password, and to sign the server response. This also means that while a proxy will forward the request, the server will never accept it as it can't decrypt the password (or rather, since the proxy has re-encrypted it with a wrong key, i'ts now completely garbled). Similarly, a client which actually checks the request authenticator in the response would not accept it.

In later extensions a Message-Authenticator was added, which signed the whole request and which the proxy can verify. Clients nowadays should always use this (e.g. FreeRadius' radtest utility does this). Many authentication schemes anyway use EAP (like Wifi/802.1x), for which the Message-Authenticator is mandatory.
As it happens, there is an upcoming feature in radsecproxy to always require a Message-Authenticator to be present. (planned for 1.11 release).

Back to your original question whether you're doing something wrong:
The best thing you are already doing: use TLS.
The only other thing that's bad is to allow client connections from 0.0.0.0/0 (unless restricted by a firewall in front). For exactly the reasons you have discovered, the allowed IP range should be kept as narrow as possible.

**Comment by gk-fschubert** [comment]
Thank you for your reply. 
It is surprising that this behavior is expected, but of course it has historical reasons. 
We currently rely on good authentication protocols and the server only accepts TLS based stuff. So IP filters have always been a mitigation and I still believe they are just that. 

We have patched the proxy so that it will not forward requests without the Message Authenticator. Since this will also be included in the next radsecproxy version, should we still open a pull request?

**Comment by fmauchle** [comment]
> We have patched the proxy so that it will not forward requests without the Message Authenticator. Since this will also be included in the next radsecproxy version, should we still open a pull request?

Thanks, no need to. My implementation is basically done, just finishing up the manpage.

**Comment by gk-fschubert** [comment]
@fmauchle thanks for the new release

Do you also have plans to implement a switch which requires the message authenticator and drop packets if it's not correct?

**Comment by fmauchle** [comment]
Yes, this is already implemented in the master branch which should be relesed soon-ish as 1.11.

In detail: message authenticator has always been validated if present (and packets dropped if invalid). New options will drop packets if message authenticator is missing.
